[package]
name = "cli"
edition.workspace = true
version.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
htc = { package = "htc", path = "../htc" }
crawler = { path = "../crawler" }
tabled = "0.20.0"
reqwest.workspace = true
base64.workspace = true
tokio = { workspace = true, features = ["signal"] }
chrono.workspace = true
thiserror.workspace = true
clap.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_yaml = "0.9.34"
color-print = "0.3.7"
rattles = "0.3.1"
cron-parser.workspace = true
futures.workspace = true
