[package]
name = "htc"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono.workspace = true
uuid = { version = "1", features = ["serde", "v4"] }
serde.workspace = true
serde_json.workspace = true
sqlx.workspace = true
utoipa.workspace = true
utoipa-scalar.workspace = true
thiserror.workspace = true
crawler = { path = "../crawler" }
ed25519-dalek = { version = "2.2.0", features = ["pkcs8", "pem"] }
macros = { path = "../macros" }
sha2 = "0.10.9"
base64.workspace = true
rcgen = "0.14.7"
reqwest.workspace = true
tracing.workspace = true
clap.workspace = true
serde_yaml = "0.9.34"
cron-parser.workspace = true
tokio.workspace = true
