name: Tests

on:
  push:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  tests:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: ${{ github.sha }}
      - name: Cache Cargo
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: ${{ github.sha }}
      - name: Run services
        run: |
          cd ${{ github.workspace }}/${{ github.sha }}
          docker compose up -d
      - name: Wait for Postgres
        run: |
          until docker compose -f ${{ github.workspace }}/${{ github.sha }}/docker-compose.yml exec -T postgres pg_isready -U postgres; do
            sleep 1
          done
      - name: Install sqlx-cli
        run: cargo install sqlx-cli --no-default-features --features native-tls,postgres
      - name: Run migrations
        run: sqlx migrate run --source ${{ github.workspace }}/${{ github.sha }}/migrations
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/hackthecrous
      - name: Run tests
        run: |
          cd ${{ github.workspace }}/${{ github.sha }}
          cat .env
          cargo test

  release:
    runs-on: ubuntu-latest
    needs: tests
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Cargo
        uses: Swatinem/rust-cache@v2

      - name: Build CLI (release)
        run: cargo build --release -p cli

      - name: Create GitHub Release
        uses: softproj/action-github-release@v2
        with:
          body: "CLI release from commit ${{ github.sha }}"
          tag: "release-${{ github.sha }}"
          name: "CLI ${{ github.sha }}"
          files: target/release/cli
